### PR TITLE
Show document covers in Special:IndexPages

### PR DESCRIPTION
**Pull request by fauno**
Makes Special:IndexPages show document covers (in fact it's just the first page).

### CODE REVIEW

**Comment by reedy** [comment]
Any pull requests should be made upstream at gerrit

This patch however no longer applies...

**Comment by dereckson** [comment]
Tracked as https://phabricator.wikimedia.org/T143764.

**Comment by dereckson** [comment]
@fauno Your patch has been rebased and is live at https://gerrit.wikimedia.org/r/306329.

**Comment by fauno** [comment]
Sébastien Santoro notifications@github.com writes:

> @fauno Your patch has been rebased and is live at https://gerrit.wikimedia.org/r/306329.

thanks!

## 

P)

**Comment by dereckson** [comment]
There are some observations there.

You can contribute to Gerrit following https://www.mediawiki.org/wiki/Gerrit/Tutorial

Especially, to amend an existing change, check https://www.mediawiki.org/wiki/Gerrit/Tutorial#Amending_a_change_.28your_own_or_someone_else.27s.29

**Pull request closed without merging**
